version: "2"

services:
  nginx-proxy:
   image: jwilder/nginx-proxy
   ports:
    - "80:80"
   networks:
    - wpdbnet
    - apachenet
    - nginxlbnet
   volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro

  apache-site-a:
   build: ./ApacheSite
   networks:
    - apachenet
   environment:
    - SITELIEN=siteA
    - VIRTUAL_HOST=sitea.${DNSNAME}

  apache-site-b:
   build: ./ApacheSite
   networks:
    - apachenet
   environment:
    - SITELIEN=siteB
    - VIRTUAL_HOST=siteb.${DNSNAME}

  phpmyadmin:
   image: phpmyadmin/phpmyadmin
   networks:
    - wpdbnet
   links:
    - "db:database"
   environment:
    - VIRTUAL_HOST=myawp.${DNSNAME}

  db:
   image: mysql
   command: --default-authentication-plugin=mysql_native_password
   networks:
    - wpdbnet
   environment:
    - MYSQL_ROOT_PASSWORD=${DBPW}
    
  wp:
   image: wordpress
   networks: 
    - wpdbnet
   environment:
    - WORDPRESS_DB_HOST=db
    - WORDPRESS_DB_USER=${DBUSER}
    - WORDPRESS_DB_PASSWORD=${DBPW}
    - WORDPRESS_DB_NAME=wpdb
    - VIRTUAL_HOST=wp.${DNSNAME}

  nginx-loadbalancer:
   build: ./nginx-load-balance
   networks:
    - nginxlbnet
   tty: true
   links:
    - nginx-site1
    - nginx-site2
   environment:
    - VIRTUAL_HOST=sitec.${DNSNAME}

  nginx-site1:
   build: ./nginx-site/siteA
   tty: true
   networks:
    - nginxlbnet

  nginx-site2:
   build: ./nginx-site/siteB
   tty: true
   networks:
    - nginxlbnet

networks:
  wpdbnet:
   driver: bridge
  apachenet:
   driver: bridge
  nginxlbnet:
   driver: bridge
